/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import MyExceptions.EmptyFieldException;
import MyExceptions.InvalidEmailFormatException;
import controlOperations.EmailValidator;
import controlOperations.PersonOperations;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import models.PersonGender;
import models.Role;

/**
 *
 * @author Zahera
 */
public class RegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterPanel
     */
    MainFrameForm mainFrame;

    public RegisterPanel(MainFrameForm mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        buttonGroup1.add(rb_male);
        buttonGroup1.add(rb_female);
        rb_male.setSelected(true);//will select male until it changed manually, benefit: no empty field exception for radioButtons
        buttonGroup2.add(rb_passenger);
        buttonGroup2.add(rb_admin);
        rb_passenger.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_firstName = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_lastName = new javax.swing.JTextField();
        cb_day = new javax.swing.JComboBox<>();
        cb_month = new javax.swing.JComboBox<>();
        rb_male = new javax.swing.JRadioButton();
        rb_female = new javax.swing.JRadioButton();
        rb_passenger = new javax.swing.JRadioButton();
        rb_admin = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_goToLogin = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        txt_birthYear = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(51, 0, 51));
        jLabel1.setFont(new java.awt.Font("Georgia", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Register Form______________________");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText(">>>First Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText(">>>Last Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText(">>>>>>>Role ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText(">>>>>>Email");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText(">>>>Password");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText(">>>>BirthDate");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText(">>>>>Gender");

        txt_firstName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_lastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cb_day.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_day.setMaximumRowCount(31);
        cb_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cb_month.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_month.setMaximumRowCount(12);
        cb_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cb_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_monthActionPerformed(evt);
            }
        });

        rb_male.setBackground(new java.awt.Color(204, 204, 255));
        rb_male.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rb_male.setForeground(new java.awt.Color(51, 51, 51));
        rb_male.setText("MALE");

        rb_female.setBackground(new java.awt.Color(204, 204, 255));
        rb_female.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rb_female.setForeground(new java.awt.Color(51, 51, 51));
        rb_female.setText("FEMALE");

        rb_passenger.setBackground(new java.awt.Color(204, 204, 255));
        rb_passenger.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rb_passenger.setForeground(new java.awt.Color(51, 51, 51));
        rb_passenger.setText("PASSENGER");

        rb_admin.setBackground(new java.awt.Color(204, 204, 255));
        rb_admin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rb_admin.setForeground(new java.awt.Color(51, 51, 51));
        rb_admin.setText("ADMIN");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("day");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("month");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 102));
        jLabel11.setText("year");

        jLabel12.setForeground(new java.awt.Color(0, 51, 102));
        jLabel12.setText("already have an account? ");

        btn_goToLogin.setBackground(new java.awt.Color(0, 51, 102));
        btn_goToLogin.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btn_goToLogin.setForeground(new java.awt.Color(255, 255, 255));
        btn_goToLogin.setText("go to login page");
        btn_goToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goToLoginActionPerformed(evt);
            }
        });

        btn_submit.setBackground(new java.awt.Color(0, 102, 153));
        btn_submit.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        txt_birthYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cb_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGap(188, 188, 188)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_male)
                                    .addComponent(rb_passenger))))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_admin)
                            .addComponent(rb_female)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(104, 104, 104)
                        .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(btn_goToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(101, 101, 101)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(183, 183, 183)
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(cb_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_birthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txt_birthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rb_male)
                    .addComponent(rb_female))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rb_passenger)
                    .addComponent(rb_admin))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit)
                    .addComponent(btn_goToLogin)
                    .addComponent(jLabel12))
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_goToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goToLoginActionPerformed
        // TODO add your handling code here:
        mainFrame.navigateToPanel("LoginPanel");
    }//GEN-LAST:event_btn_goToLoginActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        //check if there is an empty field 

        ArrayList<JTextField> textFieldsList = new ArrayList<>();
        textFieldsList.add(txt_firstName);
        textFieldsList.add(txt_lastName);
        textFieldsList.add(txt_birthYear);
        textFieldsList.add(txt_email);
        textFieldsList.add(txt_password);
        try {
            for (JTextField jTextField : textFieldsList) {
                if (jTextField.getText().trim().isEmpty()) {
                    txt_birthYear.setName(" birth year ");
                    txt_email.setName(" email ");
                    txt_firstName.setName(" first Name ");
                    txt_lastName.setName(" last Name ");
                    txt_password.setName(" password ");
                    throw new EmptyFieldException(jTextField.getName());
                }
            }
        } catch (EmptyFieldException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
            //Adding return; after showing an error message stops the method execution,
            //so the Customer won't be added unless all validation passes.
        }
        try {
            if (!EmailValidator.isValid(txt_email.getText())) {
                if (!txt_firstName.getText().trim().isEmpty()) {
                    throw new InvalidEmailFormatException(txt_email.getText(), txt_firstName.getText());
                } else {
                    throw new InvalidEmailFormatException(txt_email.getText());
                }

            }
        } catch (InvalidEmailFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
        }

        Date birthDate;
        try {
            int intYear = Integer.parseInt(txt_birthYear.getText())-1900;//from date class documentation
            int intMonth = Integer.parseInt(cb_month.getSelectedItem().toString())+1;
            int intDay = Integer.parseInt(cb_day.getSelectedItem().toString());
            birthDate = new Date(intYear, intMonth, intDay);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Number Format Exception "+e.getMessage());
            return;
        }
        PersonGender gender;
        if (rb_male.isSelected()) {
            gender = PersonGender.MALE;
        } else {
            gender = PersonGender.FEMALE;
        }
        Role role;
        if (rb_passenger.isSelected()) {
            role = Role.PASSENGER;
        } else {
            role = Role.ADMIN;
        }
        try {

            PersonOperations.registerPerson(txt_firstName.getText(),
                    txt_lastName.getText(), txt_email.getText(),
                    txt_password.getText(),
                    birthDate, gender, role);
            JOptionPane.showMessageDialog(mainFrame, "you registered successfully, \n"
                    + "\n you are able to login now", "Completed Register", JOptionPane.INFORMATION_MESSAGE);
        } catch (javax.persistence.PersistenceException e) {
            JOptionPane.showMessageDialog(mainFrame, "the email you entered is already used ,"
                    + "try another one", "persistence exception", JOptionPane.ERROR_MESSAGE);

        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(mainFrame,
                    "unexpected error happend",
                    "Runtime exception", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btn_submitActionPerformed

    private void cb_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_monthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_goToLogin;
    private javax.swing.JButton btn_submit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_day;
    private javax.swing.JComboBox<String> cb_month;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rb_admin;
    private javax.swing.JRadioButton rb_female;
    private javax.swing.JRadioButton rb_male;
    private javax.swing.JRadioButton rb_passenger;
    private javax.swing.JTextField txt_birthYear;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_password;
    // End of variables declaration//GEN-END:variables
}
