package UserInterface;

import MyExceptions.NoAvailableSeatException;
import controlOperations.FlightOperations;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import models.Airport;
import models.Flight;
import models.MyEntityController;
import models.Person;
import models.Seat;

/**
 *
 * @author Zahera
 */
public class ReservationPanel extends javax.swing.JPanel {

    MainFrameForm mainFrame;
    DefaultTableModel dtm;

    DefaultComboBoxModel comboModelorigin;
    DefaultComboBoxModel comboModeldestination;

    SpinnerNumberModel spinnerNumModel;
    Person person;
    PassengerHistory ph;

    public ReservationPanel(MainFrameForm mainFrame, Person p) {
        initComponents();
        this.mainFrame = mainFrame;
        this.person = p;
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new Object[]{
            "ID",
            "Origin",
            "Destination",
            "Capacity",
            "Departure",//YYYY-MM-DD hh:mm:ss
            "Price",
            "Available Seats"
        });
        jTable1.setModel(dtm);
        lbl_info.setText("id: " + p.getIdperson() + " , email: " + p.getEmail() + " password: " + p.getPassword());
        List<Flight> flights = FlightOperations.getAllFlights();
        ShowFlightsInTable(flights);
        comboModelorigin = new DefaultComboBoxModel();
        comboModeldestination = new DefaultComboBoxModel();
        comboModelorigin.addAll(FlightOperations.get_All_Airtports());
        comboModeldestination.addAll(FlightOperations.get_All_Airtports());
        cb_origin.setModel(comboModelorigin);
        cb_destination.setModel(comboModeldestination);

        spinnerNumModel = new SpinnerNumberModel(1, 1, 10, 1);
        spinner_seatNumber.setModel(spinnerNumModel);
        
        ph= new PassengerHistory(mainFrame,this, p);
        mainFrame.mainPanel.add(ph,"PassengerHistory");
    }
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy HH:mm");

    private void ShowFlightsInTable(List<Flight> flights) {
        for (Flight flight : flights) {
            dtm.addRow(new Object[]{
                flight.getIdflight(),
                flight.getOriginAirport(),
                flight.getDestinationAirport(),
                flight.getFlightCapacity(),
                sdf.format(flight.getDepartureDateTime()),
                flight.getSeatPrice(),
                flight.calculateAvailableSeats()
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lbl_info = new javax.swing.JLabel();
        cb_origin = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_destination = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        spinner_seatNumber = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        totalPrice = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Georgia", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Reservation Page__________________");

        lbl_info.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        lbl_info.setForeground(new java.awt.Color(0, 51, 51));
        lbl_info.setText("jLabel1");

        cb_origin.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        cb_origin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("From:");

        jLabel4.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("To");

        cb_destination.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        cb_destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_destinationActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jButton1.setText("Search for a flight");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jButton2.setText("Show all flights");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jButton3.setText("go back ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jButton4.setText("Book the selected flight");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        spinner_seatNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spinner_seatNumberMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("seat count");

        totalPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalPrice.setForeground(new java.awt.Color(0, 51, 51));
        totalPrice.setText("..................");

        jButton5.setText("total price:");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jButton6.setText("show my reservations");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(300, Short.MAX_VALUE)
                        .addComponent(lbl_info, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cb_origin, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cb_destination, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(spinner_seatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton5)
                                            .addGap(18, 18, 18)
                                            .addComponent(totalPrice)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(57, 57, 57)))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_origin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(cb_destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(spinner_seatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(totalPrice)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton3))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Airport origin = (Airport) cb_origin.getSelectedItem();
        Airport destination = (Airport) cb_destination.getSelectedItem();
        dtm.setRowCount(0);
        ShowFlightsInTable(FlightOperations.getFlights_From_TO(origin, destination));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mainFrame.navigateToPanel("LoginPanel");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dtm.setRowCount(0);
        List<Flight> flights = FlightOperations.getAllFlights();
        ShowFlightsInTable(flights);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(mainFrame, "please select a flight to complete your booking");
            return;
        }
        
        EntityManager em = MyEntityController.getEntityManager();
        int flightId = Integer.parseInt(dtm.getValueAt(jTable1.getSelectedRow(), 0).toString());
     
        Date date = new Date();
        int count = Integer.parseInt(spinner_seatNumber.getValue().toString());

        Flight f = em.find(Flight.class, flightId);
           try {
        if(count> (f.getFlightCapacity() - f.getReservationCollection().size())){
        
            throw new NoAvailableSeatException(f, count);
        }
     
            for (int i = 0; i < count; i++) {
                Seat s = FlightOperations.getAvailableSeat(f);
                if (s == null) {
                    throw new NoAvailableSeatException(f, count);
                }
                FlightOperations.makeReservation(em, f, person, s, date);
            }
        } catch (NoAvailableSeatException e) {

            JOptionPane.showMessageDialog(mainFrame, e.getMessage());
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            return;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(mainFrame, e.getMessage());
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            return;
        } finally {
            em.close();
        }
           refreshFlightsTable();
           ph.refreshReservationTable();
        JOptionPane.showMessageDialog(mainFrame, "the Reservation is CONFIRMED :)");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void spinner_seatNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spinner_seatNumberMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_spinner_seatNumberMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:  
        if (jTable1.getSelectedRow() == -1) {
            return;
        }
        float seatPrice = Float.parseFloat(dtm.getValueAt(jTable1.getSelectedRow(), 5).toString());
        int count = Integer.parseInt(spinner_seatNumber.getValue().toString());
        float total = count * seatPrice;
        totalPrice.setText(String.valueOf(total));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         mainFrame.navigateToPanel("PassengerHistory");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cb_destinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_destinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_destinationActionPerformed


public void refreshFlightsTable(){
 dtm.setRowCount(0);
        List<Flight> flights = FlightOperations.getAllFlights();
        ShowFlightsInTable(flights);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_destination;
    private javax.swing.JComboBox<String> cb_origin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_info;
    private javax.swing.JSpinner spinner_seatNumber;
    private javax.swing.JLabel totalPrice;
    // End of variables declaration//GEN-END:variables
}
